CREATE DATABASE twitter;
USE twitter;

CREATE TABLE `users` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Username` VARCHAR(60) NOT NULL,
  `Password` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE
);

CREATE TABLE `tweets` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `UserID` INT NOT NULL,
  `Content` VARCHAR(600) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE,
  CONSTRAINT `UserID` FOREIGN KEY (`UserID`) REFERENCES `twitter`.`users`(`ID`) ON DELETE CASCADE
);


CREATE TABLE `likes` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `TweetID` INT NOT NULL,
  `UserID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE,
  CONSTRAINT `TweetID` FOREIGN KEY (`TweetID`) REFERENCES `twitter`.`tweets`(`ID`) ON DELETE CASCADE,
  CONSTRAINT `LikeUserID` FOREIGN KEY (`UserID`) REFERENCES `twitter`.`users`(`ID`) ON DELETE CASCADE
);
